server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/prneje/spring-cloud-config-server-repository
          default-label: main
          username: prneje@gmail.com
          password: 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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!