server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prneje/spring-cloud-config-server-repository
          default-label: main
          username: prneje@gmail.com
          password: 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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!